root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "prettier"
extends:
  - react-app
  - react-app/jest
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
settings:
  react:
    version: detect
rules:
  "react/prop-types": off
  "react/display-name": off
  "@typescript-eslint/no-empty-function": off
  # noisy
  "@typescript-eslint/explicit-function-return-type": off
overrides:
  - files:
      - "**/__mocks__/*.ts"
      - "**/__mocks__/**/*.ts"
      - "**/*.test.ts"
      - "**/*.test.tsx"
    rules:
      "@typescript-eslint/no-var-requires": off
      "@typescript-eslint/no-empty-function": off
      "@typescript-eslint/explicit-module-boundary-types": off
      "@typescript-eslint/no-explicit-any": off
      # New tests trips on these rules, need to fix them later.
      "@typescript-eslint/no-non-null-assertion": off
      "testing-library/no-container": off
      "testing-library/no-node-access": off
      "testing-library/no-unnecessary-act": off
      "testing-library/no-wait-for-multiple-assertions": off
